services:
  traefik:                                    
    image: traefik:v3.0
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/traefik.yml:ro
      - ./traefik/acme.json:/acme.json
    networks:
      - traefik-public

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal                              # ← pas traefik-public, DB invisible depuis internet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: production
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      PORT: 3000
      NODE_ENV: production
      CLIENT_URL: https://taskmanager.com
    networks:
      - traefik-public
      - internal
    labels:                   
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.taskmanager.com`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=letsencrypt"
      - "traefik.http.services.api.loadbalancer.server.port=3000"
      - "traefik.http.routers.api-http.rule=Host(`api.taskmanager.com`)"
      - "traefik.http.routers.api-http.entrypoints=web"

  client:
    # image: taskmanagementsystem-client:latest
    build:
      context: ./client
      dockerfile: Dockerfile.prod
      args:
        VITE_API_URL: https://api.taskmanager.com/api   
    restart: unless-stopped
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.client.rule=Host(`taskmanager.com`)"
      - "traefik.http.routers.client.entrypoints=websecure"
      - "traefik.http.routers.client.tls.certresolver=letsencrypt"
      - "traefik.http.services.client.loadbalancer.server.port=80"
      - "traefik.http.routers.client-http.rule=Host(`taskmanager.com`)"
      - "traefik.http.routers.client-http.entrypoints=web"

volumes:
  postgres_data:

networks:
  traefik-public:
    external: true
  internal:
    internal: true                           